name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'  # 当打 tag 时触发发布
  pull_request:
    branches:
      - 'master'

env:
  APP_NAME: glider
  PLATFORMS: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/riscv64

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git Short SHA
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run Unit Tests
        run: go test -v .

      # Snapshot build for non-tag pushes (dev builds)
      - name: GoReleaser Snapshot Build
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Snapshot Artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v3
        with:
          name: glider-dev-${{ env.SHA_SHORT }}
          path: |
            dist/**/${{ env.APP_NAME }}*
            !dist/**/*.zip
            !dist/**/*.tar.gz

      # Release build on tag push
      - name: GoReleaser Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
